### ISSUE TITLE
v0.5.3: pimatic api requests raise "User not found" error

### ISSUE THREAD

**Issue by mwittig** [michbeck100/pimatic-echo#54] opened 2018-01-17 19:11 UTC
See https://forum.pimatic.org/topic/4101/problem-with-api-devices

Possibly caused by commit https://github.com/michbeck100/pimatic-echo/commit/c4100ca190e1f27fca4388f787b1335960e7caa5

**Comment by michbeck100** [comment] 2018-01-17 20:27
If pimatic-echo says the path /api/devices is not allowed, why doesn’t pimatic override this? Is this intended behavior?

**Comment by michbeck100** [comment] 2020-01-19 20:04
should be fixed by now

**Closed** 2020-01-19 20:04 UTC
